language: elixir

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
      env: COVERALLS=false
    - elixir: 1.4.5
      otp_release: 18.3
      env: COVERALLS=false
    - elixir: 1.4.5
      otp_release: 19.2
      env: COVERALLS=false
    - elixir: 1.4.5
      otp_release: 20.2
      env: COVERALLS=false
    - elixir: 1.5.3
      otp_release: 19.2
      env: COVERALLS=false
    - elixir: 1.5.3
      otp_release: 20.2
      env:
        COVERALLS=true
        DIALYZER=true
    - elixir: 1.6.3
      otp_release: 20.2

script:
  - ./scripts/ci_build.sh
