language: elixir

otp_release:
  - 25.0

elixir:
  - 1.13.4

jobs:
  include:
    - elixir: 1.13.4
      otp_release: 25.0
    - elixir: 1.12.3
      otp_release: 24.0

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex

install:
  - cd
  - mix do local.rebar --force, local.hex --force
  - cd -
  - mix deps.get

script:
  - ./scripts/ci_build.sh

after_success:
  - .travis/upload.sh