language: elixir

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex

matrix:
  include:
    - elixir: 1.10.4
      otp_release: 23.1

script:
  - ./scripts/ci_build.sh
