language: elixir

otp_release: 
  - 23.0

elixir:
  - 1.10.4

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex

script:
  - ./scripts/ci_build.sh
