language: elixir

otp_release: 
  - 23.0

elixir:
  - 1.10.4

jobs:
  include:
    - elixir: 1.10.4
      otp_release: 23.0
    - elixir: 1.9.4
      otp_release: 22.3
    - elixir: 1.8.2
      otp_release: 22.3
    - elixir: 1.7.4
      otp_release: 22.3
    - elixir: 1.6.6
      otp_release: 21.3
    - elixir: 1.5.3
      otp_release: 20.3

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build
    - ~/.mix
    - ~/.hex

script:
  - ./scripts/ci_build.sh
