language: elixir

cache:
  directories:
    - deps
    - _build

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
      env: COVERALLS=false
    - elixir: 1.4.5
      otp_release: 18.3
      env: COVERALLS=false
    - elixir: 1.4.5
      otp_release: 19.2
      env: COVERALLS=false
    - elixir: 1.5.1
      otp_release: 19.2
      env: COVERALLS=false
    - elixir: 1.5.1
      otp_release: 20.0
      env: COVERALLS=true

script:
  - ./scripts/ci_build.sh
